FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "main.py", "-a", "0.0.0.0", "-p", "8000", "--reload" ]